name: build-linux

on:
  workflow_dispatch:
    inputs:
      swoole_or_swow:
        required: true
        description: "定制构建选项: 构建最新版的 swoole 或者 swow （此二者扩展不能同时启用）"
        default: ' '
        type: choice
        options:
        - ' '
        - '-swoole +swoole_latest'
        - '-swoole +swow_latest'
        - '-swoole +swow'
      build_type:
        required: true
        description: "定制构建选项: 指定构建类型"
        default: 'release'
        type: choice
        options:
        - 'release'
        - 'dev'
      build_options:
        required: false
        description: "定制构建选项: 请查看 docs/options.md"
        default: ' '
        type: string
    push:

jobs:
  linux-x86_64:
    name: PHP ${{ matrix.php-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2.4"]
        # php-version: ["8.2", "8.1", "8.0"]
      max-parallel: 12
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Source Code
        run: |
          echo $PATH
          env
          docker info
          id -u
          id -g
          who
          cat /etc/os-release
          hostnamectl
          uname -s
          uname -m
          uname -r

          # echo "BUILD_PHP_VERSION=${{ matrix.php-version }}" >> "$GITHUB_ENV"

          cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
          cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l
          cat /proc/cpuinfo | grep "cpu cores" | uniq
          cat /proc/cpuinfo| grep "processor"| wc -l
          lscpu

          export IPV6=$(ip -6 address show  | grep inet6 | awk '{print $2}' | cut -d'/' -f1 | sed -n '2p')
          export IPV4=$(ip -4 address show  | grep inet | grep -v 127.0.0 | awk '{print $2}' | cut -d'/' -f1 | sed -n '1p')
          echo $IPV4
          echo $IPV6
          echo "X_IPV6=${IPV6}" >> $GITHUB_ENV
          echo "X_IPV4=${IPV4}" >> $GITHUB_ENV

          # git submodule update --init

          # 准备数据库容器
          bash sapi/src/UnitTest/scripts/database/start.sh

          # 准备数据库容器
          bash sapi/src/UnitTest/scripts/database/start.sh

      - name: Prepare Libraries and Extensions
        run: |
          set -x
          bash sapi/download-box/download-box-get-archive-from-container.sh

      - name: Prepare
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-3.17-php8-v1.0.0-x86_64-20230614T150918Z
          options: -v ${{ github.workspace }}:/work -w /work -e BUILD_PHP_VERSION=${{ matrix.php-version }}
          run: |
            set -eux
            # export PATH=/work/bin/runtime:$PATH  # 容器已经内置 php 和 composer 容器

            # composer update --no-dev  --optimize-autoloader
            composer update   --optimize-autoloader

            php prepare.php  +inotify +apcu +ds +xlswriter +ssh2 +pgsql +pdo_pgsql +mongodb --with-swoole-pgsql=1 --with-build-type=${{ inputs.build_type }} ${{ inputs.swoole_or_swow }} ${{ inputs.build_options }}  --with-install-library-cached=1

            chmod a+x make.sh
            head -n 20 make.sh

      - name: Build all-library
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-3.17-php8-v1.0.0-x86_64-20230614T150918Z
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            bash sapi/quickstart/mark-install-library-cached.sh
            bash ./make.sh all-library

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-3.17-php8-v1.0.0-x86_64-20230614T150918Z
          options: -v ${{ github.workspace }}:/work -w /work -e BUILD_PHP_VERSION=${{ matrix.php-version }}
          run: |
            bash ./make.sh config
            bash ./make.sh build
            ./php-src/sapi/cli/php -v
            bash ./make.sh archive

      - name: Show Build Result
        run: |
          ./php-src/sapi/cli/php -v
          ./php-src/sapi/cli/php -m
          ./php-src/sapi/cli/php --ri swoole
          ./bin/php-${{ matrix.php-version }}/bin/php -v
          file ./bin/php-${{ matrix.php-version }}/bin/php
          readelf -h ./bin/php-${{ matrix.php-version }}/bin/php
          ./bin/php-${{ matrix.php-version }}/bin/php -r "echo PHP_VERSION;"
          ./bin/php-${{ matrix.php-version }}/bin/php ./vendor/bin/phpunit ./sapi/src/UnitTest/MainTest.php  --list-tests
          ./bin/php-${{ matrix.php-version }}/bin/php ./vendor/bin/phpunit ./sapi/src/UnitTest/MainTest.php
          ./bin/php-${{ matrix.php-version }}/bin/php ./vendor/bin/phpunit ./sapi/src/UnitTest/SwoolePGSQLTest.php

      - name: production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: php-cli-linux-x64-${{ matrix.php-version }}
          retention-days: 7
          path: ./bin/php-${{ matrix.php-version }}/bin/php

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            php-cli-v${{ matrix.php-version }}-linux-x64.tar.xz
