name: build-php-cli-macos-x86_64

on: [ push, pull_request ]

env:
  BUILD_PHP_VERSION: 8.2.4

jobs:
  macos-x86_64:
    if: 1
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare build environment
        run: |
          env
          echo $HOME
          brew config

          brew install  wget curl  libtool automake  re2c llvm flex bison
          brew install  gettext coreutils binutils libunistring

          # brew uninstall --ignore-dependencies oniguruma
          # brew uninstall --ignore-dependencies brotli
          # brew uninstall --ignore-dependencies freetype
          # brew uninstall --ignore-dependencies zstd

          brew uninstall --ignore-dependencies snappy
          brew uninstall --ignore-dependencies capstone

          which glibtool
          ln -sf /usr/local/bin/glibtool /usr/local/bin/libtool
          ln -sf /usr/local/bin/glibtoolize /usr/local/bin/libtoolize

          # sudo rm -rf /Library/Developer/CommandLineTools
          # xcode-select --install

          # sudo xcode-select --reset
          # sudo xcode-select -switch /Library/Developer/CommandLineTools

          # softwareupdate --list --verbose
          # softwareupdate --install -a
          # xcode-select --install

          # export SDKROOT=$(xcrun --show-sdk-path)
          ls -lh $(xcrun --show-sdk-path)
          # sudo  xcode-select --switch /Applications/Xcode.app
          # export MACOSX_DEPLOYMENT_TARGET=12.6

          ifconfig
          export IPV6=$(ifconfig en0  | grep "inet6 " | grep -v "inet6 fe80:" | awk '{print $2}' | cut -d'/' -f1 | sed -n '2p')
          export IPV4=$(ifconfig en0 | grep "inet " | grep -v 127.0.0 | awk '{print $2}' | cut -d'/' -f1 | sed -n '1p')
          echo $IPV4
          echo $IPV6
          echo "X_IPV6=${IPV6}" >> $GITHUB_ENV
          echo "X_IPV4=${IPV4}" >> $GITHUB_ENV

          export PATH=/usr/local/opt/bison/bin:/usr/local/opt/llvm/bin:$PATH
          # brew bison --debug

          CURRENT_USER=$(whoami)
          echo ${CURRENT_USER}
          sudo mkdir -p /usr/local/swoole-cli
          CURRENT_USER=$(whoami) && sudo chown -R ${CURRENT_USER}:staff /usr/local/swoole-cli

          # git submodule update --init

      - name: Prepare runtime
        run: |
          mkdir -p pool/lib
          mkdir -p pool/ext
          mkdir -p bin/runtime
          bash  sapi/quickstart/setup-php-runtime.sh
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          bash sapi/download-box/download-box-get-archive-from-server.sh
      - name: prepare
        run: |
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH

          # composer update --no-dev  --optimize-autoloader
          composer update  --optimize-autoloader

          php prepare.php --without-docker=1  +ds +apcu  +xlswriter +ssh2 +pgsql +pdo_pgsql -mongodb --with-build-type=release --with-swoole-pgsql=1 --with-install-library-cached=1

      - name: Cache all-library
        uses: actions/cache@v3
        id: all-library-cache
        with:
          path: /usr/local/swoole-cli
          key: ${{ runner.os }}-build-native-php-build-all-library

      - name: Build all-library
        # if: ${{ steps.all-library-cache.outputs.cache-hit != 'true' }}
        run: |
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          bash sapi/quickstart/mark-install-library-cached.sh
          bash ./make.sh all-library

      - name: Build
        run: |
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          bash ./make.sh config
          bash ./make.sh build
          bash ./make.sh archive

      - name: Show Build Result
        run: |
          export PATH="/usr/local/opt/binutils/bin:$PATH"
          ./php-src/sapi/cli/php -v
          ./php-src/sapi/cli/php -m
          ./php-src/sapi/cli/php --ri swoole
          file ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php
          otool -L ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php
          # greadelf -h ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php
          ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php -r "echo PHP_VERSION;"
          ./php-src/sapi/cli/php ./vendor/bin/phpunit ./sapi/src/UnitTest/MainTest.php  --list-tests
          ./php-src/sapi/cli/php ./vendor/bin/phpunit ./sapi/src/UnitTest/MainTest.php

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: php-cli-macos-x64-${{ env.BUILD_PHP_VERSION }}
          retention-days: 7
          path: ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php
      - name: gh release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: php-cli-v${{ env.BUILD_PHP_VERSION }}-macos-x64.tar.xz
          draft: true
          prerelease: true
