name: build-swoole-cli-windows-cygwin

on: [ push, pull_request ]


jobs:
  windows-cygwin:
    if: 1
    runs-on: windows-2019
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          ipconfig

      - uses: actions/checkout@v3
      - name: Build TDengine
        shell: cmd
        run: ./sapi/scripts/cygwin/build-tdengine.bat
